FROM node:current-alpine

RUN mkdir -p /src/app

WORKDIR /src/app

# ENV PATH /app/node_modules/.bin:$PATH

COPY . /src/app

# COPY package.json ./
# COPY package-lock.json ./
RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent

EXPOSE 3000

# COPY . ./

CMD ["npm", "start"]
