version: '3'

services:
  api:
    build: taskAPI/
    image: tom53086/taskapi
    depends_on:
      - 'database'
    ports: 
      - '3001:3001'
    volumes:
      - ./taskapi:/src/app

  client:
    build: taskClient/
    image: tom53086/taskclient
    depends_on:
      - 'database'
    ports:
      - '3003:3000'
    volumes:
      - ./taskclient:/src/app

  database:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=tasks_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./taskdb/init.sql:/docker-entrypoint-initdb.d/init.sql