version: '3'

services:
  api:
    build: taskAPI/
    depends_on:
      - 'database'
    ports: 
      - '2000:2222'
      volumes:
      - ./taskapi:/src/app

  client:
    build: taskClient/
    depends_on:
      - 'database'
    ports:
      - '1000:1111'
    volumes:
      - ./taskclient:/src/app

  database:
    image: postgres:latest
    restart: always
    ports:
      - '3000:3333'
    environment:
      - POSTGRES_DB=tasks_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./taskdb/init.sql:/docker-entrypoint-initdb.d/init.sql