version: '3'

services:
  api:
    build: mock-taskapi/
    depends_on:
      - 'database'
    ports: 
      - '2000:2222'

  tasks:
    build: mock-task/
    depends_on:
      - 'database'
    ports:
      - '1000:1111'

  database:
    image: postgres:latest
    restart: always
    ports:
      - '3000:3333'
    environment:
      - POSTGRES_DB=emails
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql